parent_path: ""
file_check: false
processed_check: false
predicted_check: false
data_dir: h5_data
processed_dir: processed
model_predictions_dir: model_predictions
verified_predictions_dir: verified_predictions
true_dir: ground_truth
channels:
  - vhpc
  - fc
win: 5
fs: 100
