channels:
- eeg1
- eeg2
data_dir: data
file_check: false
fs: 100
features:
    - line_length
    - rms
    - mad
    - var
    - std
    - power
    - energy
    - get_envelope_max_diff
    - delta_power
    - theta_power
    - alpha_power
    - beta_power
    - gamma_power
model_id: ""
model_predictions_dir: model_predictions
parent_path: ""
predicted_check: false
processed_check: false
train_path: ""
trained_model_dir: models
processed_dir: processed
verified_predictions_dir: verified_predictions
win: 5